Repository CalmCrews/Relanz, pull requests merged in 2023-06, with the labels that each got.

#5 fix: README.md 파일 수정
  README.md
Labels: good first issue

#9 fix: README.md 수정
  README.md
Labels: good first issue

#24 feat:유저 프로필(profile->account)
  relanz/account/__init__.py
  relanz/account/admin.py
  relanz/account/apps.py
  relanz/account/migrations/0001_initial.py
  relanz/account/migrations/0002_alter_account_user_alter_account_table.py
  relanz/account/migrations/0003_alter_account_birth.py
  relanz/account/migrations/__init__.py
  relanz/account/models.py
  relanz/account/tests.py
  relanz/account/urls.py
  relanz/account/views.py
  relanz/config/settings.py
  relanz/config/urls.py
  relanz/templates/account/accountInfo.html
  relanz/templates/account/content.html
  relanz/templates/account/nickname.html
  relanz/templates/base.html
  relanz/user/views.py
Labels: ✨ Feature

#28 setting:main 만들기 및 오류 수정
  relanz/config/urls.py
  relanz/main/__init__.py
  relanz/main/admin.py
  relanz/main/apps.py
  relanz/main/migrations/__init__.py
  relanz/main/models.py
  relanz/main/tests.py
  relanz/main/urls.py
  relanz/main/views.py
  relanz/templates/account/accountInfo.html
  relanz/templates/base.html
  relanz/templates/community/detail.html
  relanz/templates/community/edit.html
  relanz/templates/community/new.html
  relanz/templates/main/home.html
  relanz/templates/user/signout.html
  relanz/user/urls.py
  relanz/user/views.py
Labels: ⚙️ Setting

#32 feature: base.css 수정
  relanz/static/css/base.css
  relanz/templates/base.html
Labels: 🎨 Html & CSS

#47 style: mobileBase.html 적용
  relanz/static/css/main/home.css
  relanz/static/css/mobileBase.css
  relanz/static/icons/Around_icon.png
  relanz/static/icons/Community_icon.png
  relanz/static/icons/Home_icon.png
  relanz/static/icons/Settings_icon.png
  relanz/templates/main/home.html
  relanz/templates/mobileBase.html
Labels: 🎨 Html & CSS

#53 fix: user 관련 디버깅
  relanz/main/views.py
  relanz/templates/mobileBase.html
  relanz/user/views.py
Labels: 🐞 BugFix

#54 Style/signup.html
  .gitignore
  relanz/community/migrations/0001_initial.py
  relanz/community/migrations/0002_initial.py
  relanz/community/migrations/0002_rename_post_article.py
  relanz/static/css/signup.css
  relanz/static/images/login/closeEye.png
  relanz/static/images/login/eye.png
  relanz/static/images/login/okIcon.png
  relanz/static/images/login/xIcon.png
  relanz/static/js/signup.js
  relanz/templates/user/signup.html
  relanz/user/migrations/0001_initial.py
Labels: 🎨 Html & CSS

#57 feature: community의 media 연결 & 이미지 업로드 구현
  relanz/community/forms.py
  relanz/community/migrations/0001_initial.py
  relanz/community/migrations/0002_alter_article_updated_at.py
  relanz/community/migrations/0003_alter_article_image.py
  relanz/community/migrations/0004_alter_article_image.py
  relanz/community/migrations/0005_remove_article_content_remove_article_title.py
  relanz/community/models.py
  relanz/community/urls.py
  relanz/community/views.py
  relanz/config/settings.py
  relanz/config/urls.py
  relanz/main/views.py
  relanz/requirements.txt
  relanz/templates/community/detail.html
  relanz/templates/community/edit.html
  relanz/templates/community/new.html
  relanz/user/views.py
Labels: ✨ Feature

#58 refactor:nickname+content 합치기
  relanz/templates/main/home.html
  relanz/templates/user/content.html
  relanz/templates/user/nickname.html
  relanz/user/urls.py
  relanz/user/views.py
Labels: 🔨 Refactor

#63 feature: content에서 survey로 넘기기
  relanz/community/migrations/0002_article_author.py
  relanz/main/views.py
  relanz/templates/main/home.html
  relanz/templates/user/accountedit.html
  relanz/templates/user/nickname.html
  relanz/templates/user/survey.html
  relanz/templates/user/userinfo.html
  relanz/user/models.py
  relanz/user/urls.py
  relanz/user/views.py
Labels: ✨ Feature

#65 feature: community pagination 기능 구현
  relanz/community/views.py
  relanz/main/views.py
  relanz/templates/community/communityHome.html
  relanz/templates/mobileBase.html
Labels: ✨ Feature

#70 fix: login 안할 시 페이지 접근불가
  relanz/challenge/models.py
  relanz/challenge/urls.py
  relanz/community/views.py
  relanz/config/settings.py
  relanz/user/views.py
Labels: 🔨 Refactor

#77 Feature/signin.html complement
  relanz/static/css/signin.css
  relanz/static/css/signup.css
  relanz/static/js/signin.js
  relanz/templates/base.html
  relanz/templates/user/signin.html
  relanz/templates/user/signup.html
Labels: 🎨 Html & CSS

#79 refactor: login error message
  relanz/config/settings.py
  relanz/user/views.py
Labels: 🔨 Refactor

#83 Style/mainpage
  relanz/community/migrations/0001_initial.py
  relanz/community/migrations/0002_initial.py
  relanz/static/css/main/home.css
  relanz/static/css/main/splashscreen.css
  relanz/templates/main/home.html
  relanz/templates/main/splashscreen.html
  relanz/user/migrations/0001_initial.py
Labels: 🎨 Html & CSS

#84 Feature: 활동시간 설문 기능 구현 완료
  relanz/config/settings.py
  relanz/templates/tag/activetime.html
  relanz/user/migrations/0002_tag.py
  relanz/user/models.py
  relanz/user/views.py
Labels: ✨ Feature

#88 Fix: migration
  relanz/community/migrations/0001_initial.py
  relanz/community/migrations/0002_initial.py
  relanz/community/migrations/0003_article_like_users.py
  relanz/community/migrations/0004_remove_article_like_users_like.py
  relanz/community/migrations/0005_alter_like_table.py
  relanz/templates/main/home.html
  relanz/templates/user/signout.html
  relanz/user/migrations/0001_initial.py
  relanz/user/migrations/0002_tag.py
  relanz/user/views.py
Labels: 🐞 BugFix

#97 Feature: 유저의 tag값을 받아서 저장
  relanz/templates/tag/tagsurvey.html
  relanz/templates/user/userinfo.html
  relanz/user/urls.py
  relanz/user/views.py
Labels: ✨ Feature

#99 style:content.html
  relanz/community/migrations/0001_initial.py
  relanz/community/migrations/0002_initial.py
  relanz/static/css/content.css
  relanz/static/icons/check_circle_down.png
  relanz/static/icons/check_circle_up.png
  relanz/static/images/contentUser.png
  relanz/static/js/content.js
  relanz/templates/user/content.html
Labels: 🎨 Html & CSS

#101 Feature/character test
  relanz/static/character/backhair/back_hair1.png
  relanz/static/character/backhair/back_hair2.png
  relanz/static/character/backhair/back_hair3.png
  relanz/static/character/backhair/back_hair4.png
  relanz/static/character/backhair/back_hair5.png
  relanz/static/character/brows/brows1.png
  relanz/static/character/brows/brows2.png
  relanz/static/character/cheeks/cheeks1.png
  relanz/static/character/cheeks/cheeks2.png
  relanz/static/character/cheeks/cheeks3.png
  relanz/static/character/eyes/eyes1.png
  relanz/static/character/eyes/eyes2.png
  relanz/static/character/face.png
  relanz/static/character/fronthair/front_hair1.png
  relanz/static/character/fronthair/front_hair2.png
  relanz/static/character/fronthair/front_hair3.png
  relanz/static/character/fronthair/front_hair4.png
  relanz/static/character/mouth/mouth1.png
  relanz/static/character/mouth/mouth2.png
  relanz/static/character/mouth/mouth3.png
  relanz/static/character/nose/nose1.png
  relanz/static/character/nose/nose2.png
  relanz/static/css/main/home.css
  relanz/templates/main/home.html
  relanz/templates/main/splashscreen.html
  relanz/templates/mobileBase.html
Labels: ✨ Feature, 🎨 Html & CSS

#100 feature: 프로필 이미지 연결 구현
  relanz/templates/user/avatar.html
  relanz/user/admin.py
  relanz/user/migrations/0002_user_avatar.py
  relanz/user/models.py
  relanz/user/urls.py
  relanz/user/views.py
Labels: ✨ Feature

#102 Input/autocomplete forbid
  relanz/static/css/content.css
  relanz/static/css/signin.css
  relanz/templates/user/content.html
  relanz/templates/user/signin.html
Labels: 🎨 Html & CSS

#103 Feature: challenge model
  relanz/challenge.json
  relanz/challenge/admin.py
  relanz/challenge/migrations/0001_initial.py
  relanz/challenge/migrations/0002_challenge_image.py
  relanz/challenge/migrations/0003_challenge_sub_effect.py
  relanz/challenge/migrations/0004_alter_challenge_image.py
  relanz/challenge/migrations/0005_alter_challenge_image.py
  relanz/challenge/models.py
  relanz/challenge/urls.py
  relanz/challenge/views.py
  relanz/config/settings.py
  relanz/config/urls.py
  relanz/static/images/challenge/jerry.gif
  relanz/static/images/challenge/tom.gif
  relanz/templates/challenge/challenge.html
  relanz/user/views.py
Labels: ✨ Feature

#107 Feature: main에 tag와 챌린지 뜰 수 있게 구현
  relanz/challenge.json
  relanz/challenge/migrations/0006_rename_recommnad_challenge_recommand.py
  relanz/challenge/models.py
  relanz/challenge/views.py
  relanz/main/views.py
  relanz/templates/main/home.html
  relanz/user/views.py
Labels: ✨ Feature

#113 style:survey.html 작성완료함
  relanz/community/migrations/0001_initial.py
  relanz/community/migrations/0002_initial.py
  relanz/static/css/signin.css
  relanz/static/css/signup.css
  relanz/static/css/survey.css
  relanz/static/css/tagsurvey.css
  relanz/static/images/faces.png
  relanz/static/images/faces_effected.png
  relanz/static/js/survey.js
  relanz/static/js/tagsurvey.js
  relanz/templates/tag/survey.html
  relanz/templates/tag/tagsurvey.html
  relanz/templates/user/signup.html
  relanz/user/migrations/0001_initial.py
  relanz/user/migrations/0002_user_avatar.py
  relanz/user/views.py
Labels: 🎨 Html & CSS

#115 feature: challenge - tag
  relanz/challenge/admin.py
  relanz/challenge/migrations/0007_participant_challenge_tag.py
  relanz/challenge/migrations/0008_rename_challenge_tag_challengetag_and_more.py
  relanz/challenge/models.py
  relanz/challenge/urls.py
  relanz/challenge/views.py
  relanz/main/views.py
  relanz/templates/challenge/challenge.html
  relanz/templates/challenge/participate.html
  relanz/user/admin.py
  relanz/user/migrations/0003_user_tag_delete_tag.py
  relanz/user/migrations/0004_rename_user_tag_usertag.py
  relanz/user/models.py
  relanz/user/views/profile_views.py
  relanz/user/views/tag_views.py
Labels: ✨ Feature

#120 style: main page
  relanz/static/css/main/home.css
  relanz/static/icons/dot.png
  relanz/templates/main/home.html
Labels: 🎨 Html & CSS

#116 feature: 아이디 찾기 구현
  .gitignore
  relanz/config/settings.py
  relanz/manage.py
  relanz/requirements.txt
  relanz/templates/user/findid.html
  relanz/templates/user/signin.html
  relanz/templates/user/signup.html
  relanz/user/migrations/0003_alter_user_email.py
  relanz/user/migrations/0004_alter_user_created_at.py
  relanz/user/models.py
  relanz/user/urls.py
  relanz/user/views/__init__.py
  relanz/user/views/find_views.py
  relanz/user/views/user_views.py
Labels: ✨ Feature

#121 fix: migration
  relanz/challenge/views.py
  relanz/community/migrations/0001_initial.py
  relanz/community/migrations/0002_alter_article_image.py
  relanz/community/migrations/0002_initial.py
  relanz/main/views.py
  relanz/user/migrations/0001_initial.py
  relanz/user/migrations/0003_alter_user_email.py
  relanz/user/migrations/0003_user_tag_delete_tag.py
  relanz/user/migrations/0004_alter_user_created_at.py
  relanz/user/migrations/0004_rename_user_tag_usertag.py
  relanz/user/views/tag_views.py
Labels: 🐞 BugFix

#125 Fix/views delete
  relanz/config/urls.py
  relanz/templates/user/signin.html
  relanz/user/urls.py
  relanz/user/views.py
  relanz/user/views/find_views.py
  relanz/user/views/tag_views.py
Labels: 🐞 BugFix

#126 Fix/typo
  relanz/templates/user/findid.html
  relanz/user/views/find_views.py
  relanz/user/views/profile_views.py
Labels: 🐞 BugFix

#127 feature: challenge-recommand 릴렌지 추천 기능(메인 홈페이지)
  relanz/main/views.py
  relanz/templates/main/home.html
Labels: ✨ Feature

#129 style:초기셋팅2000년,input값도 수정
  relanz/static/js/content.js
  relanz/templates/user/content.html
Labels: 🎨 Html & CSS

#132 style: edit home.html after signup
  relanz/templates/main/home.html
  relanz/templates/mobileBase.html
Labels: 🎨 Html & CSS

#133 fix: tag_views 복구
  relanz/templates/tag/activetime.html
  relanz/templates/tag/release.html
  relanz/templates/tag/survey.html
  relanz/user/urls.py
  relanz/user/views/tag_views.py
Labels: 🐞 BugFix

#136 Feature: 참여자수(메인, 릴렌지 상세보기) 띄우기
  relanz/challenge/admin.py
  relanz/challenge/migrations/0009_rename_challengename_challengetag_challenge.py
  relanz/challenge/migrations/0010_alter_participant_challenge.py
  relanz/challenge/models.py
  relanz/challenge/views.py
  relanz/community/migrations/0001_initial.py
  relanz/main/views.py
  relanz/templates/challenge/challenge.html
  relanz/templates/main/home.html
Labels: ✨ Feature

#141 Style/tagsurvey.html fix 해결완료 했어요~~
  relanz/static/css/tagsurvey.css
  relanz/static/js/tagsurvey.js
  relanz/templates/tag/tagsurvey.html
Labels: 🎨 Html & CSS

#142 style:signup.html 해결완료
  relanz/templates/user/signin.html
  relanz/user/views/user_views.py
Labels: 🎨 Html & CSS

#138 feature: 이메일 인증 기능 구현
  relanz/config/email_decorator.py
  relanz/config/settings.py
  relanz/config/urls.py
  relanz/main/views.py
  relanz/templates/user/activation_email.html
  relanz/templates/user/email_sent.html
  relanz/user/migrations/0002_alter_user_email.py
  relanz/user/migrations/0003_alter_user_email.py
  relanz/user/migrations/0004_user_is_email_valid.py
  relanz/user/models.py
  relanz/user/tokens.py
  relanz/user/urls.py
  relanz/user/views/profile_views.py
  relanz/user/views/tag_views.py
  relanz/user/views/user_views.py
Labels: ✨ Feature

#143 fix: signup exception 처리 및 tagsurvey 정상화
  relanz/templates/tag/tagsurvey.html
  relanz/user/views/tag_views.py
  relanz/user/views/user_views.py
Labels: 🐞 BugFix

#144 fix: usermodel-password max_length 수정
  relanz/user/migrations/0005_alter_user_password.py
  relanz/user/models.py
Labels: 🐞 BugFix

#146 fix: 이미 참여하고 있는 릴렌지는 추천 X - 예외처리
  relanz/main/views.py
  relanz/templates/challenge/challenge.html
Labels: 🐞 BugFix

#149 Style/challenge.html
  relanz/static/css/challenge.css
  relanz/static/css/main/home.css
  relanz/static/icons/check_circle_down_lean.png
  relanz/static/icons/human_shaped.png
  relanz/static/icons/map_point.png
  relanz/static/js/challenge.js
  relanz/static/js/signup_2.js
  relanz/templates/challenge/challenge.html
Labels: 🎨 Html & CSS

#148 style: remove scrollbar from mobile-content
  relanz/static/css/base.css
Labels: 🎨 Html & CSS

#152 style:participate.html
  relanz/challenge/views.py
  relanz/static/css/participate.css
  relanz/static/js/participate.js
  relanz/templates/challenge/challenge.html
  relanz/templates/challenge/participate.html
Labels: 🎨 Html & CSS

#155 style: mobile navbar change
  relanz/static/css/ranking.css
  relanz/static/icons/Home_icon.png
  relanz/static/icons/More_icon.png
  relanz/static/icons/My_icon.png
  relanz/static/icons/Ranking_icon.png
  relanz/templates/mobileBase.html
  relanz/templates/ranking.html
Labels: 🎨 Html & CSS

#157 style: home.html report summary layout
  relanz/static/css/main/home.css
  relanz/static/css/signup.css
  relanz/static/icons/report-summary.png
  relanz/static/icons/report-title.png
  relanz/templates/main/home.html
  relanz/templates/user/signup.html
Labels: 🎨 Html & CSS

#153 feature: community-participant 연결
  relanz/challenge/migrations/0011_alter_participant_table.py
  relanz/challenge/models.py
  relanz/community/migrations/0002_article_user_alter_article_author.py
  relanz/community/migrations/0003_alter_article_user.py
  relanz/community/migrations/0004_article_challenge.py
  relanz/community/migrations/0005_alter_article_challenge.py
  relanz/community/migrations/0006_alter_article_id.py
  relanz/community/migrations/0007_alter_article_id.py
  relanz/community/migrations/0008_remove_article_user.py
  relanz/community/migrations/0009_remove_article_challenge.py
  relanz/community/migrations/0010_article_challenge.py
  relanz/community/models.py
  relanz/community/urls.py
  relanz/community/views.py
  relanz/templates/community/communityHome.html
  relanz/templates/community/detail.html
  relanz/templates/community/edit.html
  relanz/templates/community/new.html
Labels: ✨ Feature

#160 style: home score section
  relanz/static/css/main/home.css
  relanz/static/icons/star30.png
  relanz/static/icons/star94.png
  relanz/templates/main/home.html
Labels: 🎨 Html & CSS

#156 Feature: 메인 리포트 통계 부분 구현
  relanz/user/migrations/0005_user_survey_result_count_alter_user_birth.py
  relanz/user/migrations/0006_alter_user_survey_result_count.py
  relanz/user/models.py
  relanz/user/views/tag_views.py
Labels: ✨ Feature

#164 style:survey 숫자기능추가
  relanz/static/js/survey.js
  relanz/templates/tag/survey.html
Labels: 🎨 Html & CSS

#159 Feature: mypage 구현, 프로필 수정하기
  relanz/main/views.py
  relanz/templates/user/content.html
  relanz/templates/user/userinfo.html
  relanz/user/urls.py
  relanz/user/views/profile_views.py
Labels: ✨ Feature

#162 refactor: avatar page for editing
  relanz/templates/mobileBase.html
  relanz/templates/user/avatar.html
Labels: 🔨 Refactor

#163 feature: score 구현
  relanz/community/migrations/0011_article_article_score.py
  relanz/community/models.py
  relanz/community/views.py
  relanz/templates/challenge/challenge.html
  relanz/templates/community/communityHome.html
  relanz/user/migrations/0006_user_score.py
  relanz/user/models.py
Labels: ✨ Feature

#167 Feature: 랭킹 페이지 기능 구현
  relanz/main/urls.py
  relanz/main/views.py
  relanz/templates/main/ranking.html
  relanz/user/models.py
Labels: ✨ Feature

#170 feature: main-page second.report 알고리즘 구현
  relanz/main/__init__.py
  relanz/main/views/__init__.py
  relanz/main/views/home_views.py
  relanz/main/views/ranking_views.py
Labels: ✨ Feature

#171 Style/community home.html
  relanz/static/css/communityHome.css
  relanz/static/icons/loading.png
  relanz/static/images/leein_example.jpeg
  relanz/static/js/communityHome.js
  relanz/templates/community/communityHome.html
Labels: 🎨 Html & CSS

#172 fix:tag_views 와 content.js 를 통해 오류수정
  relanz/static/js/content.js
  relanz/templates/tag/survey.html
  relanz/templates/user/content.html
  relanz/user/migrations/0008_merge_0006_user_score_0007_merge_20230630_0002.py
  relanz/user/views/tag_views.py
Labels: 🎨 Html & CSS

#173 Style: email sent 구현 완료
  relanz/main/views/home_views.py
  relanz/static/css/main/home.css
  relanz/static/css/user/email_sent.css
  relanz/static/icons/alert.png
  relanz/static/icons/close.png
  relanz/templates/main/home.html
  relanz/templates/user/avatar.html
  relanz/templates/user/email_sent.html
  relanz/user/views/tag_views.py
  relanz/user/views/user_views.py
Labels: 🎨 Html & CSS

#176 fix: home views.py except 처리
  relanz/main/views/home_views.py
Labels: 🐞 BugFix

#177 fix:단순 오류수정
  relanz/static/js/communityHome.js
  relanz/static/js/content.js
  relanz/templates/user/content.html
  relanz/user/migrations/0001_initial.py
  relanz/user/migrations/0002_alter_user_email.py
  relanz/user/migrations/0003_alter_user_email.py
  relanz/user/migrations/0004_user_is_email_valid.py
  relanz/user/migrations/0005_alter_user_password.py
  relanz/user/migrations/0005_user_survey_result_count_alter_user_birth.py
  relanz/user/migrations/0006_alter_user_survey_result_count.py
  relanz/user/migrations/0006_user_score.py
  relanz/user/migrations/0007_merge_20230630_0002.py
  relanz/user/migrations/0008_merge_0006_user_score_0007_merge_20230630_0002.py
Labels: 🎨 Html & CSS

#178 feature: edit-tag user tag 보내기
  relanz/user/views/tag_views.py
Labels: ✨ Feature
